---
title: "Coachella Over The Years"
author: "Owen Halpert"
date: "2023-02-14"
output: html_document
---

## Homework Week 7

Initial visualizations of the Coachella 2023 and 2022 playlists!

```{r setup, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(spotifyr)
library(ggplot2)
library(ggthemes)
library(tidyverse)
coachella2023 <- get_playlist_audio_features("", "2HfbF1Xx4RHhJI8jNvQAQb")
coachella2022 <- get_playlist_audio_features("", "2tcwxeUSNT7gYMzidaf5W1")
```

```{r mutate, echo=FALSE}
coachella20232 <- coachella2023 %>%               
  mutate(
    mode = ifelse(mode == 0, "Minor", "Major")
  )
coachella20222 <- coachella2022 %>%               
  mutate(
    mode = ifelse(mode == 0, "Minor", "Major")
  )
```


```{r graph1, echo=FALSE}
ggplot(coachella20222, aes(x = valence, y = energy, size = danceability, color = mode)) +
  geom_point(position = "jitter", alpha = 0.4) +
  labs(x = "Valence", y = "Energy", color = "Mode", size = "Danceability", title = "Coachella 2022") +
  theme_fivethirtyeight()
```

```{r graph2, echo=FALSE}
ggplot(coachella20232, aes(x = valence, y = energy, size = danceability, color = mode)) +
  geom_point(position = "jitter", alpha = 0.4) +
  labs(x = "Valence", y = "Energy", color = "Mode", size = "Danceability", title = "Coachella 2023") +
  theme_fivethirtyeight()
```


